### ISSUE TITLE
Reduce permission scope to Documents

### ISSUE THREAD

**Issue by danirabbit** [raibtoffoletto/litteris#21]
Hey there, I saw your note on [the review PR](https://github.com/elementary/appcenter-reviews/pull/136) about wanting to give users a way to use sync apps with Litteris and that makes sense! I think we should still probably scope things down though to just the documents folder and not the whole home folder :)

**Comment by raibtoffoletto** [comment]
@danrabbit The problem is: giving the choice to point to where the user actually keeps its cloud directory.

I, for example, keep a `~/Nextcloud` and a `~/Dropbox`. My `Documents` dir is specific for docs in each machine. I totally understand your concern for the scope, but I'm not sure how to tackle this... keeping a list of possible cloud dirs in `~/` is unmaintainable and keeping access only to `~/Documents` would break this feature (at least for me, probably the only one using it in a regular basis). I had this discussion when I published on flathub and in the end we left at `~/`... What the EOS team thinks?

**Comment by danirabbit** [comment]
Thanks for following up! That sounds reasonable enough for now. Something to keep in mind is that as time goes on we do want to work towards complete confinement, and it is planned to have AppCenter start warning about apps who request filesystem access outside if the file chooser portal. So I would recommend thinking about and working on a way to scope down file access.

**Comment by raibtoffoletto** [comment]
@danrabbit   Yes, I agree that for this case the app shouldn't have any access to the personal folder. I think the way forward for flatpacks would be able to ask other apps for permission and create links with their sandbox (iOS works like that if I'm not mistaken), so if I wanted a synced DB I should be able to just ask for the NextCloud flatpak for access to it's synced folder.
